### ISSUE TITLE
Context tags propagation using W3C Baggage specification

### ISSUE THREAD

**Issue by duxet** [kamon-io/Kamon#979] opened 2021-03-31 13:28 UTC
There is another emerging W3C standard defining `baggage` header, which could be a good way to propagate Kamon context tags: https://w3c.github.io/baggage/

**Comment by duxet** [comment] 2021-04-01 14:38
The biggest problem I see is that baggage header might contain additional metadata (properties), which isn't present in Kamon context:

```
key1=value1;property1;property2, key2 = value2, key3=value3; propertyKey=propertyValue
```

We could just treat it as a part of tag value, but it doesn't seem to be a perfect solution.

**Comment by SimunKaracic** [comment] 2021-04-01 14:57
We'll probably just add a prefix to every key so we know what to parse

**Comment by jmendesky** [comment] 2021-04-21 16:33
I believe this duplicates https://github.com/kamon-io/Kamon/issues/803 :)

is there any plan for this to be implemented in the near future?

**Comment by SimunKaracic** [comment] 2021-04-22 09:28
No plans right now, there's more urgent things on our plate right now.
We do accept community contributions though :D

**Comment by jmendesky** [comment] 2021-04-22 11:31
:D we were thinking about that. 
I suppose w3c baggage would be an alternative serialisation format to what is present at the moment (context-tags)? 
Also, would it make sense to not support properties in the beginning? Its usage is not 100% clear and the w3c spec doesn't even show them in their examples. Without properties, the spec would be compatible with Kamon's context.

**Comment by ivantopo** [comment] 2021-04-23 08:08
Hey folks, indeed this is a duplicate of #803 so I'm going to go ahead and close this to continue the chat there.

**Closed by ivantopo** 2021-04-23 08:08 UTC
