### ISSUE TITLE
Kamon corrupting Akka config

### ISSUE THREAD

**Issue by japgolly** [kamon-io/Kamon#511] opened 2018-02-03 05:24 UTC
I just added Kamon to an Akka project being used at my job and found an issue. As per the instructions I added Kamon config to the `application.conf` being shared by Akka and discovered that if I initialised Kamon before Akka, then it corrupted the config and prevented Akka working correctly.

I'm at home now but the code was something along these lines:

```scala
object MainApp {
  def main(args: Array[String]): Unit = {
    Kamon.loadReportersFromConfig()
    initialiseAndStartAkkaCluster()
  }
}

class App extends Actor {
}
```

which was meant to be run locally like `sbt run -DHTTP_PORT=1234 -DCLUSTER_PORT=5678`.

The code above would seem to work but then nodes within the cluster wouldn't be able to talk to each other; they'd spout ConnectionRefused errors.

**This issue presents even without any instrumenting, akka or otherwise.** With only `kamon-core` (and maybe also `kamon-jaeger`) on the classpath the error was occurring.

Once I traced the issued down to config corruption, I ensured that I didn't reference Kamon until Akka was up and it fixed everything! The workaround looked like this:

```scala
object MainApp {
  def main(args: Array[String]): Unit = {
    initialiseAndStartAkkaCluster()
  }
}

class App extends Actor {
    Kamon.loadReportersFromConfig()
}
```

Also FYI I ensured I was using the latest versions of akka, kamon, and everything else.

**Comment by ivantopo** [comment] 2018-02-03 12:03
Hey @japgolly, glad you made it work, but none of that should be necessary! Were you able to pinpoint what settings were being corrupted? When Kamon starts it only reads the configuration, there is no writing nor anything like that, there are no APIs in the Config object for that so there has to be something else happening here.

Could you please share your classpath? maybe we left some bad stuff in our configs :(

**Comment by japgolly** [comment] 2018-02-05 03:07
No unfortunately I don't know what it does to the config. I forgot to mention that the cli args seem to disappear. So remember how I said we start the app like "sbt 'run -DHTTP_PORT=1234 -DCLUSTER_PORT=5678'"?, if Kamon goes first the HTTP_PORT and CLUSTER_PORT seem to disappear, in addition to it preventing cluster node communicating.

Classpath is:
```
org/typelevel/cats-jvm_2.12/0.9.0/cats-jvm_2.12-0.9.0.jar
org/spire-math/jawn-parser_2.12/0.11.0/jawn-parser_2.12-0.11.0.jar
com/typesafe/akka/akka-cluster_2.12/2.5.9/akka-cluster_2.12-2.5.9.jar
ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar
org/scalaz/scalaz-core_2.12/7.2.17/scalaz-core_2.12-7.2.17.jar
io/netty/netty-handler/4.0.52.Final/netty-handler-4.0.52.Final.jar
com/typesafe/akka/akka-distributed-data_2.12/2.5.9/akka-distributed-data_2.12-2.5.9.jar
com/google/firebase/firebase-admin/5.4.0/firebase-admin-5.4.0.jar
com/lihaoyi/fastparse_2.12/0.4.4/fastparse_2.12-0.4.4.jar
com/google/api-client/google-api-client-gson/1.22.0/google-api-client-gson-1.22.0.jar
com/fasterxml/jackson/module/jackson-module-scala_2.12/2.8.9/jackson-module-scala_2.12-2.8.9.jar
io/kamon/kamon-akka-2.5_2.12/1.0.1/kamon-akka-2.5_2.12-1.0.1.jar
org/asynchttpclient/async-http-client/2.0.37/async-http-client-2.0.37.jar
org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar
org/typelevel/macro-compat_2.12/1.1.1/macro-compat_2.12-1.1.1.jar
io/swagger/swagger-core/1.5.16/swagger-core-1.5.16.jar
io/kamon/kamon-prometheus_2.12/1.0.0/kamon-prometheus_2.12-1.0.0.jar
com/ibm/watson/developer_cloud/alchemy/3.5.1/alchemy-3.5.1.jar
com/typesafe/akka/akka-protobuf_2.12/2.5.9/akka-protobuf_2.12-2.5.9.jar
org/asynchttpclient/async-http-client-netty-utils/2.0.37/async-http-client-netty-utils-2.0.37.jar
com/typesafe/netty/netty-reactive-streams/1.0.8/netty-reactive-streams-1.0.8.jar
org/typelevel/cats-kernel_2.12/1.0.1/cats-kernel_2.12-1.0.1.jar
com/typesafe/akka/akka-persistence_2.12/2.5.9/akka-persistence_2.12-2.5.9.jar
com/ibm/watson/developer_cloud/core/3.5.1/core-3.5.1.jar
com/typesafe/akka/akka-actor_2.12/2.5.9/akka-actor_2.12-2.5.9.jar
com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
org/codehaus/jackson/jackson-core-asl/1.9.11/jackson-core-asl-1.9.11.jar
com/github/jnr/jnr-posix/3.0.27/jnr-posix-3.0.27.jar
com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9.jar
com/typesafe/akka/akka-stream_2.12/2.5.9/akka-stream_2.12-2.5.9.jar
org/http4s/http4s-core_2.12/0.16.6a/http4s-core_2.12-0.16.6a.jar
com/google/auth/google-auth-library-oauth2-http/0.8.0/google-auth-library-oauth2-http-0.8.0.jar
org/typelevel/machinist_2.12/0.6.2/machinist_2.12-0.6.2.jar
org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar
com/google/api/grpc/proto-google-iam-v1/0.1.12/proto-google-iam-v1-0.1.12.jar
org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4.jar
org/lmdbjava/lmdbjava/0.6.0/lmdbjava-0.6.0.jar
org/agrona/agrona/0.9.12/agrona-0.9.12.jar
org/glassfish/jersey/bundles/repackaged/jersey-jsr166e/2.22.2/jersey-jsr166e-2.22.2.jar
com/uber/jaeger/jaeger-core/0.21.0/jaeger-core-0.21.0.jar
com/ibm/watson/developer_cloud/conversation/3.5.1/conversation-3.5.1.jar
org/scalaz/stream/scalaz-stream_2.12/0.8.6a/scalaz-stream_2.12-0.8.6a.jar
org/typelevel/cats-core_2.12/1.0.1/cats-core_2.12-1.0.1.jar
org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar
io/circe/circe-core_2.12/0.9.0/circe-core_2.12-0.9.0.jar
com/github/jnr/jffi/1.2.16/jffi-1.2.16-native.jar
io/dropwizard/metrics/metrics-core/3.2.2/metrics-core-3.2.2.jar
org/springframework/spring-core/4.3.7.RELEASE/spring-core-4.3.7.RELEASE.jar
backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
org/hdrhistogram/HdrHistogram/2.1.9/HdrHistogram-2.1.9.jar
io/circe/circe-generic_2.12/0.9.0/circe-generic_2.12-0.9.0.jar
org/scala-lang/modules/scala-parser-combinators_2.12/1.0.4/scala-parser-combinators_2.12-1.0.4.jar
org/scala-sbt/test-interface/1.0/test-interface-1.0.jar
com/ibm/watson/developer_cloud/dialog/3.5.1/dialog-3.5.1.jar
com/ibm/watson/developer_cloud/language-translator/3.5.1/language-translator-3.5.1.jar
org/http4s/http4s-client_2.12/0.16.6a/http4s-client_2.12-0.16.6a.jar
com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar
com/squareup/okhttp3/logging-interceptor/3.3.1/logging-interceptor-3.3.1.jar
com/typesafe/akka/akka-cluster-tools_2.12/2.5.9/akka-cluster-tools_2.12-2.5.9.jar
com/fasterxml/jackson/module/jackson-module-paranamer/2.8.9/jackson-module-paranamer-2.8.9.jar
com/google/guava/guava/20.0/guava-20.0.jar
io/kamon/kamon-jaeger_2.12/1.0.1/kamon-jaeger_2.12-1.0.1.jar
org/log4s/log4s_2.12/1.4.0/log4s_2.12-1.4.0.jar
io/opentracing/opentracing-noop/0.30.0/opentracing-noop-0.30.0.jar
com/ibm/watson/developer_cloud/java-sdk/3.5.1/java-sdk-3.5.1.jar
io/aeron/aeron-client/1.7.0/aeron-client-1.7.0.jar
commons-lang/commons-lang/2.6/commons-lang-2.6.jar
org/scalaz/scalaz-effect_2.12/7.2.8/scalaz-effect_2.12-7.2.8.jar
org/http4s/http4s-parboiled2_2.12/0.16.6a/http4s-parboiled2_2.12-0.16.6a.jar
org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar
io/circe/circe-jawn_2.12/0.9.0/circe-jawn_2.12-0.9.0.jar
com/github/jnr/jnr-ffi/2.1.6/jnr-ffi-2.1.6.jar
com/ibm/watson/developer_cloud/retrieve-and-rank/3.5.1/retrieve-and-rank-3.5.1.jar
com/google/http-client/google-http-client-appengine/1.21.0/google-http-client-appengine-1.21.0.jar
org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar
org/threeten/threetenbp/1.3.3/threetenbp-1.3.3.jar
io/opentracing/opentracing-api/0.30.0/opentracing-api-0.30.0.jar
com/ibm/watson/developer_cloud/visual-recognition/3.5.1/visual-recognition-3.5.1.jar
com/google/http-client/google-http-client-gson/1.22.0/google-http-client-gson-1.22.0.jar
junit/junit/4.12/junit-4.12.jar
com/squareup/okhttp3/okhttp-ws/3.3.1/okhttp-ws-3.3.1.jar
org/scodec/scodec-bits_2.12/1.1.2/scodec-bits_2.12-1.1.2.jar
com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.8.9/jackson-dataformat-yaml-2.8.9.jar
org/apache/httpcomponents/httpasyncclient/4.1.1/httpasyncclient-4.1.1.jar
com/fasterxml/jackson/core/jackson-databind/2.8.9/jackson-databind-2.8.9.jar
io/aeron/aeron-driver/1.7.0/aeron-driver-1.7.0.jar
org/json/json/20160810/json-20160810.jar
com/joestelmach/natty/0.11/natty-0.11.jar
com/typesafe/akka/akka-persistence-cassandra_2.12/0.80/akka-persistence-cassandra_2.12-0.80.jar
com/typesafe/akka/akka-remote_2.12/2.5.9/akka-remote_2.12-2.5.9.jar
com/google/cloud/google-cloud-core/1.2.1/google-cloud-core-1.2.1.jar
com/lihaoyi/sourcecode_2.12/0.1.4/sourcecode_2.12-0.1.4.jar
com/google/auto/value/auto-value/1.2/auto-value-1.2.jar
org/asynchttpclient/netty-codec-dns/2.0.37/netty-codec-dns-2.0.37.jar
org/typelevel/discipline_2.12/0.7.2/discipline_2.12-0.7.2.jar
de/heikoseeberger/akka-http-circe_2.12/1.19.0/akka-http-circe_2.12-1.19.0.jar
io/netty/netty-transport/4.0.52.Final/netty-transport-4.0.52.Final.jar
ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar
io/kamon/kamon-core_2.12/1.0.1/kamon-core_2.12-1.0.1.jar
com/typesafe/config/1.3.2/config-1.3.2.jar
com/typesafe/akka/akka-persistence-query_2.12/2.5.8/akka-persistence-query_2.12-2.5.8.jar
io/kamon/kamon-scala-future_2.12/1.0.0/kamon-scala-future_2.12-1.0.0.jar
org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar
com/ibm/watson/developer_cloud/natural-language-classifier/3.5.1/natural-language-classifier-3.5.1.jar
javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
com/ibm/watson/developer_cloud/speech-to-text/3.5.1/speech-to-text-3.5.1.jar
org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar
com/github/japgolly/microlibs/stdlib-ext_2.12/1.13/stdlib-ext_2.12-1.13.jar
org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar
org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar
com/ibm/watson/developer_cloud/tradeoff-analytics/3.5.1/tradeoff-analytics-3.5.1.jar
com/ibm/watson/developer_cloud/tone-analyzer/3.5.1/tone-analyzer-3.5.1.jar
com/lihaoyi/fastparse-utils_2.12/0.4.4/fastparse-utils_2.12-0.4.4.jar
com/google/protobuf/protobuf-java-util/3.3.0/protobuf-java-util-3.3.0.jar
com/ibm/watson/developer_cloud/language-translation/3.5.1/language-translation-3.5.1.jar
org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.jar
org/reflections/reflections/0.9.11/reflections-0.9.11.jar
org/typelevel/scala-library/2.12.1/scala-library-2.12.1.jar
io/netty/netty-buffer/4.0.52.Final/netty-buffer-4.0.52.Final.jar
org/typelevel/catalysts-platform_2.12/0.0.5/catalysts-platform_2.12-0.0.5.jar
org/http4s/http4s-async-http-client_2.12/0.16.6a/http4s-async-http-client_2.12-0.16.6a.jar
com/ibm/watson/developer_cloud/personality-insights/3.5.1/personality-insights-3.5.1.jar
io/opentracing/opentracing-util/0.30.0/opentracing-util-0.30.0.jar
javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
org/http4s/http4s-websocket_2.12/0.2.0/http4s-websocket_2.12-0.2.0.jar
com/typesafe/akka/akka-http-core_2.12/10.0.11/akka-http-core_2.12-10.0.11.jar
org/mnode/ical4j/ical4j/1.0.2/ical4j-1.0.2.jar
com/ibm/watson/developer_cloud/text-to-speech/3.5.1/text-to-speech-3.5.1.jar
com/github/jnr/jnr-constants/0.9.9/jnr-constants-0.9.9.jar
com/google/cloud/google-cloud-core-http/1.2.1/google-cloud-core-http-1.2.1.jar
com/typesafe/akka/akka-http_2.12/10.0.11/akka-http_2.12-10.0.11.jar
io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar
com/google/http-client/google-http-client-jackson/1.21.0/google-http-client-jackson-1.21.0.jar
org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar
de/heikoseeberger/akka-sse_2.12/2.0.0-M5/akka-sse_2.12-2.0.0-M5.jar
org/scalacheck/scalacheck_2.12/1.13.4/scalacheck_2.12-1.13.4.jar
com/datastax/cassandra/cassandra-driver-core/3.4.0/cassandra-driver-core-3.4.0.jar
io/circe/circe-parser_2.12/0.9.0/circe-parser_2.12-0.9.0.jar
io/verizon/delorean/core_2.12/1.2.40-scalaz-7.2/core_2.12-1.2.40-scalaz-7.2.jar
io/swagger/swagger-annotations/1.5.16/swagger-annotations-1.5.16.jar
org/typelevel/cats-kernel-laws_2.12/0.9.0/cats-kernel-laws_2.12-0.9.0.jar
io/netty/netty-common/4.0.52.Final/netty-common-4.0.52.Final.jar
com/google/api/api-common/1.1.0/api-common-1.1.0.jar
com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar
io/kamon/kamon-executors_2.12/1.0.1/kamon-executors_2.12-1.0.1.jar
ch/megard/akka-http-cors_2.12/0.2.2/akka-http-cors_2.12-0.2.2.jar
org/apache/httpcomponents/httpcore-nio/4.4.4/httpcore-nio-4.4.4.jar
org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
org/typelevel/cats-free_2.12/0.9.0/cats-free_2.12-0.9.0.jar
com/google/protobuf/protobuf-java/3.3.0/protobuf-java-3.3.0.jar
io/netty/netty-codec/4.0.52.Final/netty-codec-4.0.52.Final.jar
commons-logging/commons-logging/1.2/commons-logging-1.2.jar
com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.jar
com/fasterxml/jackson/core/jackson-core/2.8.9/jackson-core-2.8.9.jar
org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar
org/typelevel/catalysts-macros_2.12/0.0.5/catalysts-macros_2.12-0.0.5.jar
com/squareup/okhttp3/okhttp/3.8.1/okhttp-3.8.1.jar
org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2.jar
com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.jar
io/swagger/swagger-scala-module_2.12/1.0.4/swagger-scala-module_2.12-1.0.4.jar
com/google/apis/google-api-services-storage/v1-rev100-1.22.0/google-api-services-storage-v1-rev100-1.22.0.jar
org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar
com/squareup/okhttp3/okhttp-urlconnection/3.3.1/okhttp-urlconnection-3.3.1.jar
org/nanohttpd/nanohttpd/2.3.1/nanohttpd-2.3.1.jar
com/typesafe/akka/akka-slf4j_2.12/2.5.9/akka-slf4j_2.12-2.5.9.jar
com/google/api/gax/1.4.1/gax-1.4.1.jar
io/circe/circe-numbers_2.12/0.9.0/circe-numbers_2.12-0.9.0.jar
io/spray/spray-json_2.12/1.3.3/spray-json_2.12-1.3.3.jar
io/swagger/swagger-jaxrs/1.5.16/swagger-jaxrs-1.5.16.jar
com/google/auth/google-auth-library-credentials/0.8.0/google-auth-library-credentials-0.8.0.jar
org/apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar
org/typelevel/cats-laws_2.12/0.9.0/cats-laws_2.12-0.9.0.jar
com/github/swagger-akka-http/swagger-akka-http_2.12/0.11.0/swagger-akka-http_2.12-0.11.0.jar
com/google/api-client/google-api-client/1.22.0/google-api-client-1.22.0.jar
org/asynchttpclient/netty-resolver-dns/2.0.37/netty-resolver-dns-2.0.37.jar
com/typesafe/akka/akka-http-spray-json_2.12/10.0.10/akka-http-spray-json_2.12-10.0.10.jar
com/typesafe/akka/akka-parsing_2.12/10.0.11/akka-parsing_2.12-10.0.11.jar
com/google/cloud/google-cloud-storage/1.2.1/google-cloud-storage-1.2.1.jar
com/chuusai/shapeless_2.12/2.3.3/shapeless_2.12-2.3.3.jar
org/typelevel/cats-macros_2.12/1.0.1/cats-macros_2.12-1.0.1.jar
com/ccadllc/cedi/config_2.12/1.1.0/config_2.12-1.1.0.jar
com/github/jnr/jffi/1.2.16/jffi-1.2.16.jar
com/ibm/watson/developer_cloud/document-conversion/3.5.1/document-conversion-3.5.1.jar
org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar
commons-codec/commons-codec/1.9/commons-codec-1.9.jar
org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar
com/github/julien-truffaut/monocle-core_2.12/1.4.0/monocle-core_2.12-1.4.0.jar
com/typesafe/akka/akka-cluster-sharding_2.12/2.5.9/akka-cluster-sharding_2.12-2.5.9.jar
com/google/oauth-client/google-oauth-client/1.22.0/google-oauth-client-1.22.0.jar
org/typelevel/cats_2.12/0.9.0/cats_2.12-0.9.0.jar
com/squareup/okio/okio/1.13.0/okio-1.13.0.jar
com/lihaoyi/fansi_2.12/0.2.4/fansi_2.12-0.2.4.jar
org/asynchttpclient/netty-resolver/2.0.37/netty-resolver-2.0.37.jar
com/github/mpilquist/simulacrum_2.12/0.10.0/simulacrum_2.12-0.10.0.jar
io/swagger/swagger-models/1.5.16/swagger-models-1.5.16.jar
io/netty/netty-codec-http/4.0.52.Final/netty-codec-http-4.0.52.Final.jar
joda-time/joda-time/2.9.2/joda-time-2.9.2.jar
org/scalaz/scalaz-concurrent_2.12/7.2.8/scalaz-concurrent_2.12-7.2.8.jar
com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar
com/fasterxml/jackson/core/jackson-annotations/2.8.9/jackson-annotations-2.8.9.jar
com/uber/jaeger/jaeger-thrift/0.21.0/jaeger-thrift-0.21.0.jar
org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar
com/google/api/grpc/proto-google-common-protos/0.1.12/proto-google-common-protos-0.1.12.jar
org/ow2/asm/asm/5.0.3/asm-5.0.3.jar
```

**Comment by ivantopo** [comment] 2018-02-09 23:04
Hey @japgolly, were you able to figure this out? If not, you mentioned above that you added some kamon-specific configuration to your `application.conf` file, could you please share that? maybe there is something weird in the additional configuration. I noticed with one of our users a couple days ago a funny character that looks like double quotes but isn't a double quote, on the filters section.

Please take a very careful look at the config and share it if possible, thanks!

**Comment by japgolly** [comment] 2018-02-28 10:13
Hi @ivantopo, I'm back at work next week and will have a look then

**Comment by ivantopo** [comment] 2018-08-22 06:10
hey @japgolly, long time has passed since this.. I'm going to close the issue because we couldn't find a way to reproduce the issue, feel free to reopen it and share any additional info if it comes up. Thanks!

**Closed by ivantopo** 2018-08-22 06:10 UTC
Labels: Planned for Next Release
