### ISSUE TITLE
Kamon 0.4.0 Memory leak with Spray.

### ISSUE THREAD

**Issue by tsukaby** [kamon-io/Kamon#213] opened 2015-06-04 11:57 UTC
Hi! Kamon developers.
Thank you for release 0.4.0!

I did update my program from 0.3.5 to 0.4.0.
But I got a memory leak problem with following environments.

- Scala 2.11.6
- Kamon 0.4.0 (core, spray, statsd, datadog, system-metrics, sigar-loader)
- Spray 1.3.2 (can, routing, json, client)
- aspectjweaver 1.7.4

a part of application.conf

```
kamon.metric {
  disable-aspectj-weaver-missing-error = true

  filters {
    akka-actor {
      includes = [ "**" ]
      excludes = [ "*/system/**", "appname/user/io-http/**" ]
    }
    trace {
      includes = [ "**" ]
      excludes = []
    }
    akka-dispatcher {
      includes = [ "**" ]
      excludes = []
    }
  }
}
```

Statistics via jvisualvm.
![java_visualvm](https://cloud.githubusercontent.com/assets/6133458/7983430/1e5154c2-0afb-11e5-94cc-7456745eea62.png)

Heap dump via jvisualvm.
![java_visualvm](https://cloud.githubusercontent.com/assets/6133458/7983460/7496a9ea-0afb-11e5-8726-699eee7ec33b.png)
![java_visualvm](https://cloud.githubusercontent.com/assets/6133458/7983521/1d06358c-0afc-11e5-9649-eec42a372d3c.png)

I think it caused by spray-client or ActorCell.

My program used hostConnector in spray-client.  
Problem occured when it used. My test running mode that not occured because spray-client doesn't used. (I used mock client)

Do you have any solutions or ideas? I did disable metrics of akka-actor now. (`akka-actor.includes = []`)

Sorry I have poor skill of English. (I am Japanese speaker.)

**Comment by nilsga** [comment] 2015-07-07 11:34
I think this is similar to an issue we are seeing. Have you been able to find the cause, or have you put it on hold?

**Comment by szimano** [comment] 2015-07-20 09:19
I am experiencing a very similar problem using aspectjweaver 1.8.6. any ideas?

**Comment by ivantopo** [comment] 2015-07-20 12:53
@tsukaby thanks for sharing this! As @nilsga mentioned, this probably is related to the issue he fixed with #229, given the fact that your dump shows that you have tons of min max counters in memory it is almost certain that the issue is related to that.. so, cold you please try the very latest snapshot that contain that fix? That would be `0.4.1-2ce80225a5ae4d0ed7ba53be1ebe0734d4e4bca6` from our snapshots repo at http://snapshots.kamon.io, hope that the issue is gone there!

**Comment by tsukaby** [comment] 2015-07-20 15:09
Thank you fix and build! I'm going to try it on this week.

I will contact you again later.

**Comment by tsukaby** [comment] 2015-07-21 05:03
Thank you @nilsga !
Tnank you @ivantopo !

This problem solved on our system. (use `0.4.1-2ce80225a5ae4d0ed7ba53be1ebe0734d4e4bca6`)

### before (`0.4.0`)

![java_visualvm_before](https://cloud.githubusercontent.com/assets/6133458/8793407/16d3e612-2fb1-11e5-8235-fb5cded589b0.png)

### after (`0.4.1-2ce80225a5ae4d0ed7ba53be1ebe0734d4e4bca6`)

![java_visualvm_after](https://cloud.githubusercontent.com/assets/6133458/8793412/224d37d2-2fb1-11e5-88fd-3d6135b6b78d.png)

Thanks a lot!

**Closed** 2015-07-21 05:04 UTC

**Comment by jozic** [comment] 2015-07-21 15:24
@ivantopo 
when do you guys plan to release 0.4.1 with this fix?

**Comment by ivantopo** [comment] 2015-07-21 15:27
It should happen really, really soon. I find it weird that not too many people complained, yet 0.4.0 is by far the most downloaded version we have! If possible, please use the snapshot now and then switch to 0.4.1 when it becomes available!

**Comment by tsukaby** [comment] 2015-07-21 15:32
I'm also waiting for the next release.
However, we are satisfied with the snapshot for now. (We are used it in production environment. :yum: )

Thank you!

**Comment by jozic** [comment] 2015-07-21 17:56
thanks! I saw similar issue with lots of memory consumed after we started app with Kamon, but did have a chance to verify the exact reason.
Will try snapshot and crossing fingers for the soon release :)

**Comment by dodnert** [comment] 2015-08-13 21:14
FYI - My project was impacted by this issue as well. Using version `0.4.1-2ce80225a5ae4d0ed7ba53be1ebe0734d4e4bca6`, the problem was resolved.
