### ISSUE TITLE
Illegal reflective access by kamon.instrumentation.executor.ExecutorInstrumentation

### ISSUE THREAD

**Issue by kunalherkal** [kamon-io/Kamon#890] opened 2020-11-09 16:51 UTC
Whenever our sbt application starts, we notice these warning logs in `stderr`. Most of the metrics for executor service are working. Some metrics are not working, for these I have created another issue #891 I do not know if these two issues are related.

```
WARNING: An illegal reflective access operation has occurred
WARNING: All illegal access operations will be denied in a future release
WARNING: Illegal reflective access by kamon.instrumentation.executor.ExecutorInstrumentation$ (file:/opt/blah-blach/lib/io.kamon.kamon-bundle_2.12-2.1.8.jar) to field java.util.concurrent.Executors$DelegatedExecutorService.e
WARNING: Please consider reporting this to the maintainers of kamon.instrumentation.executor.ExecutorInstrumentation$
```

Here are the kamon dependencies we use:
```
"io.kamon" %% "kamon-bundle" % "2.1.8"
"io.kamon" %% "kamon-influxdb" % "2.1.8"
"io.kamon" %% "kamon-prometheus" % "2.1.8"
"io.kamon" % "kanela-agent" % "1.0.7"
```
Other details:
```
scalaVersion: 2.12.8, 
sbtVersion: 1.4.2
openjdk version "11.0.2" 2019-01-15
```

**Comment by SimunKaracic** [comment] 2020-11-11 14:57
Hey, you can find a temp workaround for that here -> https://github.com/kamon-io/Kamon/issues/641#issuecomment-674413950

Workaround isn't forever though, we'll get around to fixing it

**Comment by ivantopo** [comment] 2022-03-04 12:59
Closing this as duplicate of #641

**Closed by ivantopo** 2022-03-04 12:59 UTC
Labels: duplicate
