### ISSUE TITLE
Kamon with Lagom

### ISSUE THREAD

**Issue by Arpit1596** [kamon-io/Kamon#623] opened 2019-12-05 11:55 UTC
I want to use use kamon with lagom.

I added the kamon bundle in my application and kanela-plugin, as per the documentation kanela should automatically start and instrumentation should begin but nothing happens.

Moreover I want to use log-reporter but I am not able to find "factory" to provide in the config file to use kamon-log-reporter module.

I added this plugin :-

```
addSbtPlugin("io.kamon" % "sbt-kanela-runner" % "2.0.3")
```
This is my build.sbt file:-
```
val kamon = "io.kamon" %% "kamon-bundle" % "2.0.4"
val logReporter = "io.kamon" %% "kamon-log-reporter" % "0.6.8"

lazy val `root` = (project in file("."))
  .enablePlugins(JavaAgent)
  .aggregate(`root-api`, `root-impl`)
  .settings(libraryDependencies in ThisBuild ++= Seq(macwire,kamon,logReporter))
  .settings(
    credentials += Credentials(Path.userHome / ".sbt" / ".credentials")
  )
  .settings(
    javaOptions in Universal += "-DKamon.auto-start=true",
  )
```
This is my log-reporter conf:-

```
kamon{
  modules{
      enabled = true
      name ="LOG REPORTER"
      description = "Logs the metrics"
      factory = "" //don't know what to add here
      }
     }
```

This is the repo link :- https://github.com/Arpit1596/lagom-kamon-example

**Comment by ihostage** [comment] 2019-12-05 16:16
Hi, @Arpit1596! 👋 
1. Duplicate of https://github.com/kamon-io/Kamon/issues/563
2. Kamon has a [repository](https://github.com/kamon-io/kamon-lagom), where will implement integration with Lagom.
3. Kamon works fine with Lagom only on PROD-mode. With DEV-mode instrumentation not work until.
4. Metrics for Lagom Circuit Breakers already implemented on this [pull request](https://github.com/kamon-io/kamon-play/pull/56) and will be moved to the special repository (see point 2).

**Comment by ivantopo** [comment] 2020-09-10 07:39
I'm closing this issue because it is either too old to be relevant or stale. Stop by our [Github Discussions](https://github.com/kamon-io/Kamon/discussions) section and drop a message if you need any additional help with the topic.

Have a nice day!

**Closed by ivantopo** 2020-09-10 07:39 UTC
