### ISSUE TITLE
[Feature request] Support instrumentation of akka typed actors

### ISSUE THREAD

**Issue by kpritam** [kamon-io/Kamon#679] opened 2019-12-18 16:51 UTC
From akka 2.6.x, [akka typed](https://doc.akka.io/docs/akka/current/typed/actors.html) actors APIs are marked as stable. 
It would be really nice to provide support for typed actors.

**Comment by bitbeter** [comment] 2020-11-20 10:37
Is there any open-tracing solution for akka typed  ?!

**Comment by SimunKaracic** [comment] 2020-11-20 11:19
Can you point me to any specific problems you have with akka-typed actors? 
As far as I can tell, they're getting traced correctly, but there's some issues with actor class names and auto-grouping that are fixed in this PR https://github.com/kamon-io/Kamon/pull/898 which should be merged soon!

**Comment by bitbeter** [comment] 2020-11-20 12:08
@SimunKaracic 
Ooo, Maybe I'm wrong
I create simple project with java based akka-typed application (BehaviorAbstract, EventSourced, ...] and i run this command for creating "Jeager all-in-one" application
```bash 
docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 14250:14250 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.20
```

and setup configs to this

```conf
kamon {
  jaeger {
    enabled = true
    # Define the host/port where the Jaeger Collector/Agent is listening.
    host = "localhost"
    port = 14268

    # Protocol used to send data to Jaeger. The available options are:
    #   - http: Sends spans using jaeger.thrift over HTTP (collector).
    #   - https: Sends spans using jaeger.thrift over HTTPS (collector).
    #   - udp: Sends spans using jaeger.thrift compact over UDP (agent).
    protocol = HTTP
    # Enable or disable including tags from kamon.environment as labels
     include-environment-tags = no
  }
}
```

```java
public class Main {
    public static void main(String[] args) {
        Kamon.init();
        ActorSystem.create(MainSystem.create(), MainSystem.NAME);
    }
}
```

but nothing I saw in Jeager client at all, i saw just Jeager itself query traces. 

then I saw this issue, so i was thinking, kamon library may not working for typed, and then i ask the question ...

Any extra thing I forgot to do ?

**Comment by SimunKaracic** [comment] 2020-11-20 12:20
Try adding kamon.trace.sampler="always" to the kamon configuration!

If that doesn't work, you can try sharing the code with me so I can try and reproduce it!
I've been using the akka quickstart example to try the tracing out

**Comment by SimunKaracic** [comment] 2020-11-20 12:38
Also, actors won't start spans by themselves, they'll merely be part of the trace. 
Checkout this answer (the `Kamon.runWithSpan` part is what you might need) if you don't have any http calls or something else that will start a trace
https://github.com/kamon-io/Kamon/discussions/896#discussioncomment-127527

**Comment by n3ziniuka5** [comment] 2020-11-22 20:14
> Can you point me to any specific problems you have with akka-typed actors?

Current examples in the documentation show context propagation with classic actors and they don't mention anything about akka-typed. So, does context propagation actually work with akka-typed? If so, how does it pass the context?

**Comment by SimunKaracic** [comment] 2020-11-23 14:22
Typed actors get transformed into untyped actors of class `ActorAdapter`, and they (both typed and untyped actors) run on the same ActorSystem. A great side benefit of that (for us) is that we don't have to change anything for tracing and context propagation, since the underlying mechanisms/runtime are the same whether you use typed or untyped actors.

> ... examples in the documentation ...

Are you refering to this page? https://kamon.io/docs/latest/instrumentation/akka/context-propagation/
If so, all of that works exactly the same for typed actors.
Besides some of the tag changes (in the PR linked above), there's nothing really new that need to be done.

If you have a specific example, let me know, we want typed actors to have the same coverage as classic ones

**Comment by n3ziniuka5** [comment] 2020-11-23 16:15
> Are you refering to this page? https://kamon.io/docs/latest/instrumentation/akka/context-propagation/
> If so, all of that works exactly the same for typed actors.
> Besides some of the tag changes (in the PR linked above), there's nothing really new that need to be done.
> 
> If you have a specific example, let me know, we want typed actors to have the same coverage as classic ones

Yes, I was referring to that page. I think even if examples are with classic actors, it would be good to list akka-typed support as an explicit feature in the documentation. I doubt I was the only one who got the impression that Kamon only supports untyped actors.

Apart from that, I don't have a concrete example of something that's not working in akka-typed and am looking forward to start using Kamon in akka-typed systems now. Thanks!

**Comment by SimunKaracic** [comment] 2021-01-20 11:03
We're updating the documentation to show a akka-typed example!
I'm closing this, if you see any problems with akka-typed please open an issue!

**Closed by SimunKaracic** 2021-01-20 11:03 UTC
