### ISSUE TITLE
Kamon fluentd integration with elasticsearch not working

### ISSUE THREAD

**Issue by sk3749614** [kamon-io/Kamon#373] opened 2016-07-13 10:37 UTC
I am trying to send Kamon statistics to elastic search through fluentd. Elastic Search is rejecting the requests with the following error:
MapperParsingException[Field name [app.name] cannot contain '.']

The field names are hardcoded in Fluentd.scala. Is there any way to work around this?

**Comment by dpsoft** [comment] 2016-07-13 13:52
@everpeace ping!!!

**Comment by everpeace** [comment] 2016-07-14 07:18
@sk3749614 Hi! thank you for trying Kamon fluentd integration.

Fluentd is really flexible and extensible by design.  There are bunch of plugins in community.  By using those plugin, you can transform metrics in your own way.  

In your case, I suppose that you could use field name(key name) by using [rename-key plugin](https://github.com/shunwen/fluent-plugin-rename-key) or similar one.

**Comment by sk3749614** [comment] 2016-07-15 03:03
Thanks for the reply. rename-key did not have a filter option. I used
https://github.com/mjourard/fluent-plugin-json-transform and built it
locally. It is working now. It does seem quite simple to build our own
plugins. Should give it a try.

**Comment by everpeace** [comment] 2016-07-15 07:56
@sk3749614 @dpsoft could you please close this issue? Thanks!

**Closed** 2016-07-16 11:53 UTC

**Comment by dpsoft** [comment] 2016-07-16 11:57
@everpeace thanks for the support.
