### ISSUE TITLE
Error java.lang.ClassNotFoundException: kamon.log.LogbackFilter for kamon 2.3.1 with play and prometheus

### ISSUE THREAD

**Issue by YuHuang89** [kamon-io/Kamon#1070] opened 2021-11-03 10:40 UTC
I was trying to add kamon with prometheus to a Play hello word project. When I start the application with "sbt run", there is an Error 
"ERROR in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Could not create component [filter] of type [kamon.log.LogbackFilter] java.lang.ClassNotFoundException: kamon.log.LogbackFilter
        at java.lang.ClassNotFoundException: kamon.log.LogbackFilter
"
and the reporter wasn't started on port 9095 successfully.

build.sbt: 
"io.kamon" %% "kamon-bundle" % "2.3.1",
"io.kamon" %% "kamon-prometheus" % "2.3.1"

project/plugins.sbt:
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.8")
addSbtPlugin("io.kamon" % "sbt-kanela-runner-play-2.8" % "2.0.12")

I have attached the code in the zip file.
[play-samples-play-scala-hello-world-tutorial.zip](https://github.com/kamon-io/Kamon/files/7466900/play-samples-play-scala-hello-world-tutorial.zip)
![image](https://user-images.githubusercontent.com/21994860/140045715-9005b649-d05c-44be-a208-9f6c28f5d81f.png)
![image](https://user-images.githubusercontent.com/21994860/140045772-268992df-8d87-4170-9929-69c6fd953dd3.png)
![image](https://user-images.githubusercontent.com/21994860/140045953-964b887f-6f52-4427-807b-a22f7b717256.png)

**Comment by antoine-morisseau** [comment] 2021-12-08 10:19
I think the 2.4.0 fix this issue because with my tests of upgrading Kamon between 2.3.X and 2.4.X, this issue disappeared.

I think it's this commit that fix the issue : https://github.com/kamon-io/Kamon/commit/d37cb4884def81b9ad8bcea914d4c8ac2da6d4c2

**Comment by ivantopo** [comment] 2022-03-01 15:13
Indeed, this issue was fixed in [v2.4.0](https://github.com/kamon-io/Kamon/releases/tag/v2.4.0) and was caused by a rouge `logback.xml` file in the mongo instrumentation. Thanks for bringing it up and thanks @antoine-morisseau for doing the research!

**Closed by ivantopo** 2022-03-01 15:13 UTC
